USE my_db;

DROP TABLE IF EXISTS workouts;
DROP TABLE IF EXISTS current;

CREATE TABLE workouts (
  id INT PRIMARY KEY AUTO_INCREMENT,
  the_date CHAR(100) NOT NULL,
  workout CHAR (100) NOT NULL,
  duration CHAR (100) NOT NULL
);

CREATE TABLE current (
  id INT PRIMARY KEY AUTO_INCREMENT,
  the_date CHAR(100) NOT NULL,
  workout CHAR (100) NOT NULL,
  duration CHAR (100) NOT NULL
);
